import React, { useState } from 'react';
import { AnalysisReport, Marker, LayerType, Persona } from '../types';
import { Download, Users, Lock, Share2, Check, Heart, Brain, Lightbulb } from 'lucide-react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import LeadModal from './LeadModal';
import { saveLead } from '../services/supabaseService';
import { EMOTIONS } from '../constants';

interface ReportPanelProps {
  report: AnalysisReport | null;
  markers: Marker[];
  isAnalyzing: boolean;
  currentUrl: string;
  activeLayer: LayerType;
  setActiveLayer: (layer: LayerType) => void;
}

const UnlockOverlay: React.FC<{ onUnlock: () => void }> = ({ onUnlock }) => (
    <div className="absolute inset-0 bg-white/50 backdrop-blur-md z-10 flex flex-col items-center justify-center p-8 text-center">
        <div className="w-16 h-16 bg-lem-orange/10 rounded-full flex items-center justify-center mb-4">
            <Lock size={32} className="text-lem-orange" />
        </div>
        <h3 className="text-lg font-bold text-gray-900">Unlock Deep Insights</h3>
        <p className="text-sm text-gray-600 my-2">Get detailed persona breakdowns, psychological needs analysis, and a strategic design brief.</p>
        <button onClick={onUnlock} className="mt-4 bg-lem-orange text-white font-bold py-2 px-6 rounded-lg shadow-md hover:bg-orange-600 transition-all">
            Unlock Full Report
        </button>
    </div>
);

const PersonaCard: React.FC<{ persona: Persona }> = ({ persona }) => (
    <div className="p-4 border border-gray-200 rounded-lg bg-white shadow-sm">
        <div className="flex items-start gap-3">
            <div className="w-10 h-10 bg-orange-100 rounded-full flex-shrink-0 flex items-center justify-center text-lem-orange">
                <Users size={20} />
            </div>
            <div>
                <h4 className="font-bold text-gray-900">{persona.name}</h4>
                <p className="text-xs text-gray-500 font-medium">{persona.role}</p>
            </div>
            <span className="ml-auto text-xs font-semibold bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">{persona.techLiteracy} Tech</span>
        </div>
        <p className="text-xs text-gray-500 italic my-3 p-3 bg-gray-50 rounded-md">"{persona.quote}"</p>
        <div className="text-xs space-y-2">
            <p><strong className="font-bold text-gray-800">Bio:</strong> {persona.bio}</p>
            <p><strong className="font-bold text-gray-800">Goals:</strong> {persona.goals}</p>
            <p><strong className="font-bold text-gray-800">Psychographics:</strong> {persona.psychographics}</p>
            {persona.values?.length > 0 && <p><strong className="font-bold text-gray-800">Values:</strong> {persona.values.join(', ')}</p>}
            {persona.frustrations?.length > 0 && <p><strong className="font-bold text-gray-800">Frustrations:</strong> {persona.frustrations.join(', ')}</p>}
        </div>
    </div>
);

const ReportPanel: React.FC<ReportPanelProps> = ({ report, markers, isAnalyzing, currentUrl, activeLayer, setActiveLayer }) => {
  const [showLeadModal, setShowLeadModal] = useState(false);
  const [isUnlocked, setIsUnlocked] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  
  const generatePDF = () => {
    if (!report) return;

    const doc = new (jsPDF as any)({ orientation: 'p', unit: 'mm', format: 'a4' });
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    const margin = 15;
    let yOffset = margin;

    const addPageWithHeader = () => {
        doc.addPage();
        addHeader();
    };
    
    const addHeader = () => {
        yOffset = margin;
        doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor('#F26522');
        doc.text('LEM', margin, yOffset);
        doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor('#555555');
        doc.text('by METODIC', margin + 12, yOffset);
        doc.setFontSize(8); doc.setTextColor('#6B7280');
        doc.text(`Analysis: ${currentUrl}`, pageWidth - margin, yOffset, { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin, yOffset + 3, { align: 'right' });
        yOffset += 5;
        doc.setDrawColor('#F26522'); doc.setLineWidth(0.5); doc.line(margin, yOffset, pageWidth - margin, yOffset);
        yOffset += 10;
    };

    const addFooter = () => {
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8); doc.setTextColor('#6B7280');
            doc.text(`Page ${i} of ${pageCount} - Generated by LEMtool AI`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        }
    };
    
    addHeader();

    // --- Section: UX Emotion Score ---
    doc.setFillColor('#F9FAFB'); doc.setDrawColor('#E5E7EB');
    doc.roundedRect(margin, yOffset, pageWidth - 2 * margin, 30, 5, 5, 'FD');
    doc.setFillColor('#FFF7ED');
    doc.roundedRect(margin, yOffset + 25, pageWidth - 2 * margin, 5, 5, 5, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor('#6B7280');
    doc.text('UX EMOTION SCORE', margin + 5, yOffset + 7);
    doc.setFontSize(22); doc.setTextColor('#F26522');
    doc.text(`${report.overallScore}/100`, margin + 5, yOffset + 20);
    const circleX = pageWidth - margin - 15; const circleY = yOffset + 15;
    doc.setDrawColor('#F26522'); doc.setLineWidth(1.5); doc.circle(circleX, circleY, 10, 'D');
    doc.setFontSize(14); doc.setTextColor('#374151');
    doc.text(markers.length.toString(), circleX, circleY + 4, { align: 'center' });
    doc.setFontSize(8); doc.setTextColor('#6B7280');
    doc.text('TOTAL INSIGHTS', circleX, circleY + 14, { align: 'center' });
    yOffset += 40;

    // --- Section: Executive Summary ---
    doc.setFontSize(12); doc.setTextColor('#374151'); doc.setFont('helvetica', 'bold');
    doc.text('Executive Summary', margin, yOffset); yOffset += 5;
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor('#4B5563');
    const summaryLines = doc.splitTextToSize(report.summary, pageWidth - 2 * margin);
    doc.text(summaryLines, margin, yOffset + 4);
    yOffset += (summaryLines.length * 4) + 10;
    
    // --- Personas Section ---
    if (yOffset + 50 > pageHeight - margin) { addPageWithHeader(); }
    doc.setFontSize(12); doc.setTextColor('#374151'); doc.setFont('helvetica', 'bold');
    doc.text('Deep Personas', margin, yOffset); yOffset += 8;
    
    report.personas.forEach(p => {
        const personaCardHeight = 40 + doc.splitTextToSize(p.bio, pageWidth - 2 * margin - 15).length * 3 + doc.splitTextToSize(p.goals, pageWidth - 2 * margin - 15).length * 3 + doc.splitTextToSize(p.quote, pageWidth - 2 * margin - 15).length * 4;
        if (yOffset + personaCardHeight > pageHeight - margin) { addPageWithHeader(); }
        
        let personaContentY = yOffset + 5;
        doc.setFillColor('#F9FAFB'); doc.setDrawColor('#E5E7EB');
        doc.roundedRect(margin, yOffset, pageWidth - 2 * margin, personaCardHeight, 3, 3, 'FD');
        
        doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor('#374151');
        doc.text(p.name, margin + 5, personaContentY); personaContentY += 4;
        doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor('#6B7280');
        doc.text(p.role, margin + 5, personaContentY); personaContentY += 6;

        doc.setFontSize(8); doc.setFont('helvetica', 'italic');
        const quoteLines = doc.splitTextToSize(`"${p.quote}"`, pageWidth - 2 * margin - 10);
        doc.text(quoteLines, margin + 5, personaContentY); personaContentY += (quoteLines.length * 3) + 4;
        
        doc.setFont('helvetica', 'normal');
        const bioLines = doc.splitTextToSize(`Bio: ${p.bio}`, pageWidth - 2 * margin - 10);
        doc.text(bioLines, margin + 5, personaContentY); personaContentY += (bioLines.length * 3) + 4;
        
        const goalsLines = doc.splitTextToSize(`Goals: ${p.goals}`, pageWidth - 2 * margin - 10);
        doc.text(goalsLines, margin + 5, personaContentY);
        
        yOffset += personaCardHeight + 5;
    });

    // ... continue with other sections like SDT, Creative Brief etc. ...
    
    addFooter();
    doc.save(`LEM_Analysis_${new Date().toISOString().slice(0, 10)}.pdf`);
  };


  const handleShare = async () => {
    const shareUrl = `${window.location.origin}?target=${encodeURIComponent(currentUrl)}`;
    if (navigator.share) {
      try {
        await navigator.share({ title: `LEMtool AI Analysis for ${currentUrl}`, url: shareUrl });
      } catch (error) {
        navigator.clipboard.writeText(shareUrl);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
      }
    } else {
      navigator.clipboard.writeText(shareUrl);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };
  
  const handleLeadSubmit = async (name: string, email: string) => {
    await saveLead(name, email, currentUrl);
    setIsUnlocked(true);
    setShowLeadModal(false);
  };

  const TabButton = ({ layer, label, icon }: { layer: LayerType, label: string, icon: React.ReactNode }) => (
    <button onClick={() => setActiveLayer(layer)} className={`flex-grow flex items-center justify-center gap-2 py-3 text-sm font-bold border-b-2 transition-all ${activeLayer === layer ? 'text-lem-orange border-lem-orange' : 'text-gray-400 border-transparent hover:text-gray-700'}`}>{icon}{label}</button>
  );

  const renderEmptyState = () => (
    <div className="h-full flex flex-col items-center justify-center p-8 text-center text-gray-400">
      <div className="w-24 h-24 bg-gray-100 rounded-full mb-6 flex items-center justify-center border-4 border-gray-200">
        <span className="text-4xl">...</span>
      </div>
      <h3 className="font-bold text-gray-600">Enter a URL to generate an emotional profile.</h3>
    </div>
  );
  
  if (isAnalyzing) return <div className="h-full flex items-center justify-center text-gray-400 text-sm">Thinking...</div>;
  if (!report) return renderEmptyState();

  return (
    <>
      <LeadModal isOpen={showLeadModal} onClose={() => setShowLeadModal(false)} onSubmit={handleLeadSubmit} websiteUrl={currentUrl} />
      <div className="h-full flex flex-col bg-white">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold text-gray-900">Analysis</h2>
            <div className="flex items-center gap-2">
              <button onClick={handleShare} className="p-2 rounded-lg border border-gray-300 text-gray-500 hover:bg-gray-100">{isCopied ? <Check size={16} /> : <Share2 size={16} />}</button>
              <button onClick={() => isUnlocked ? generatePDF() : setShowLeadModal(true)} className="flex items-center gap-1.5 text-sm font-bold px-3 py-2 rounded-lg bg-gray-800 text-white hover:bg-black">{isUnlocked ? <Download size={14} /> : <Lock size={14} />}{isUnlocked ? 'Download PDF' : 'Full Report'}</button>
            </div>
          </div>
          <div className="flex items-center justify-between bg-gray-800 text-white p-4 rounded-xl shadow-lg">
            <div><div className="text-xs text-gray-400 uppercase tracking-wider font-semibold">UX Emotion Score</div><div className="text-3xl font-bold">{report.overallScore}/100</div></div>
            <div className="flex flex-col items-center"><div className="h-12 w-12 rounded-full border-4 border-lem-orange flex items-center justify-center bg-gray-700"><span className="text-lg font-bold">{markers.length}</span></div><div className="text-[10px] text-gray-400 uppercase tracking-wider font-semibold mt-1">Total Insights</div></div>
          </div>
        </div>
        
        <nav className="flex border-b border-gray-200 bg-gray-50/50 flex-shrink-0">
           <TabButton layer="emotions" label="Emotions" icon={<Heart size={14} />} />
           <TabButton layer="needs" label="Psych Needs" icon={<Brain size={14} />} />
           <TabButton layer="strategy" label="Strategy" icon={<Lightbulb size={14} />} />
        </nav>

        <div className="flex-1 overflow-y-auto p-6 relative">
          {!isUnlocked && <UnlockOverlay onUnlock={() => setShowLeadModal(true)} />}
          <div className={!isUnlocked ? 'filter blur-sm select-none pointer-events-none opacity-50' : ''}>
              {activeLayer === 'emotions' && (
                <div className="space-y-6">
                  <div>
                    <h3 className="font-bold mb-2 text-gray-900">Executive Summary</h3>
                    <p className="text-sm text-gray-600 bg-gray-50 p-3 rounded-lg border">{report.summary}</p>
                  </div>
                  <div>
                    <h3 className="font-bold mb-4 text-gray-900">Deep Personas</h3>
                    <div className="space-y-4">
                       {report.personas.map((p, index) => <PersonaCard key={p.name + index} persona={p} />)}
                    </div>
                  </div>
                </div>
              )}
              {activeLayer === 'needs' && (
                <div className="space-y-6">
                  <h3 className="font-bold mb-4 text-gray-900">Psychological Needs (SDT)</h3>
                  <div className="space-y-4 p-4 bg-gray-50 rounded-lg border">
                    <div>
                      <div className="flex justify-between text-sm font-bold mb-1 text-gray-800"><p>Autonomy</p><p>{report.sdtScores.autonomy.score}/100</p></div>
                      <div className="w-full bg-gray-200 rounded-full h-2"><div className="bg-blue-500 h-2 rounded-full" style={{width: `${report.sdtScores.autonomy.score}%`}}></div></div>
                       <p className="text-xs text-gray-500 mt-1">{report.sdtScores.autonomy.justification}</p>
                    </div>
                     <div>
                      <div className="flex justify-between text-sm font-bold mb-1 text-gray-800"><p>Competence</p><p>{report.sdtScores.competence.score}/100</p></div>
                      <div className="w-full bg-gray-200 rounded-full h-2"><div className="bg-green-500 h-2 rounded-full" style={{width: `${report.sdtScores.competence.score}%`}}></div></div>
                       <p className="text-xs text-gray-500 mt-1">{report.sdtScores.competence.justification}</p>
                    </div>
                     <div>
                      <div className="flex justify-between text-sm font-bold mb-1 text-gray-800"><p>Relatedness</p><p>{report.sdtScores.relatedness.score}/100</p></div>
                      <div className="w-full bg-gray-200 rounded-full h-2"><div className="bg-pink-500 h-2 rounded-full" style={{width: `${report.sdtScores.relatedness.score}%`}}></div></div>
                       <p className="text-xs text-gray-500 mt-1">{report.sdtScores.relatedness.justification}</p>
                    </div>
                  </div>
                </div>
              )}
              {activeLayer === 'strategy' && (
                 <div className="space-y-6">
                    <h3 className="font-bold mb-4 text-gray-900">Strategic Creative Brief</h3>
                    <div className="p-4 bg-gray-50 border rounded-lg space-y-3">
                      <p className="text-sm text-gray-700"><strong className="text-gray-900">Problem:</strong> {report.creativeBrief.problemStatement}</p>
                       <p className="text-sm font-bold text-gray-900 border-t border-gray-200 pt-3 mt-3">How might we: <span className="font-normal text-blue-600">{report.creativeBrief.howMightWe}</span></p>
                       <p className="text-sm text-gray-700"><strong className="text-gray-900">Direction:</strong> {report.creativeBrief.strategicDirection}</p>
                       <p className="text-sm text-gray-700"><strong className="text-gray-900">Target Emotion:</strong> {report.creativeBrief.targetEmotion}</p>
                    </div>
                 </div>
              )}
          </div>
        </div>
      </div>
    </>
  );
};

export default ReportPanel;